version: '3.9'
services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - db

volumes:
  pgdata:
