version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: seven-seas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Max-payne2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: mah01134212100/seven-seas
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seven-seas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Max-payne2
    depends_on:
      - db

volumes:
  pgdata: